[package]
name = "anonymiser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
itertools = "0.10.1"
fake = "2.4"
rand = "0.8"
