[package]
name = "anonymiser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16 = "0.2.1"
base32 = "0.4.0"
chrono = "0.4"
itertools = "0.10.1"
fake = "2.4"
lazy_static = "1.4.0"
postgres = "0.19.2"
rand = "0.8"
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
uuid = { version = "0.8", features = [ "v4"] }
