#!/bin/bash

set -exu

# the tag should increment the previous tag on github here(https://github.com/Multiverse-io/anonymiser/tags)
tag=$1;

if [[ ! $tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
then
  echo "tag should be in the format '0.1.1'";
  exit 1;
fi


#Horrible hack with the .bak due to how mac-os sed works.. this is ugly but should work on both linux and mac-os
sed -i.bak "s/^version = \".*\"$/version = \"$tag\"/" Cargo.toml
rm -f Cargo.tom.bak


echo "building x86_64-unknown-linux-musl"
./release_scripts/x86_64-unknown-linux-musl/create_release
echo "building x86_64-unknown-linux-gnu"
./release_scripts/x86_64-unknown-linux-gnu/create_release
echo "aarch64-apple-darwin"
./release_scripts/aarch64-apple-darwin/create_release
echo "x86_64-apple-darwin"
./release_scripts/x86_64-apple-darwin/create_release


gh release create "v$tag" './anonymiser-x86_64-unknown-linux-gnu#General linux' './anonymiser-x86_64-unknown-linux-musl#Alpine linux' './anonymiser-x86_64-apple-darwin#Intel Mac' './anonymiser-aarch64-apple-darwin#Apple silicon mac'
