#!/bin/bash
set -e

export CARGO_NET_GIT_FETCH_WITH_CLI=true

cargo install cargo2junit
cargo fmt -- --check
cargo test -- -Z unstable-options --format json --report-time | cargo2junit > results.xml
exit ${PIPESTATUS[0]}
