#!/bin/bash

set -exu

# the tag should increment the previous tag on github here(https://github.com/Multiverse-io/anonymiser/tags)
tag=$1;

if [[ ! $tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
then
  echo "tag should be in the format 'v0.1.1'";
  exit 1;
fi

# Remove v prefix from tag
version="${tag:1}"

#Horrible hack with the .bak due to how mac-os sed works.. this is ugly but should work on both linux and mac-os
sed -i.bak "s/^version = \".*\"$/version = \"$version\"/" Cargo.toml
rm -f Cargo.toml.bak
