#!/bin/bash

sudo docker build -t release-image -f - . << EOF
  FROM rust:latest AS builder

  RUN rustup target add x86_64-unknown-linux-musl
  RUN apt update
  RUN apt install -y musl-tools musl-dev build-essential
  RUN yes | apt install gcc-x86-64-linux-gnu

  COPY ./ .

  # set correct linker
  ENV RUSTFLAGS='-C linker=x86_64-linux-gnu-gcc'

  RUN cargo build --target x86_64-unknown-linux-musl --release
  RUN ls
  RUN cp target/x86_64-unknown-linux-musl/release/anonymiser ./anonymiser
EOF
sudo docker run -td --name release-container release-image
sudo docker cp release-container:anonymiser ./anonymiser-x86_64-unknown-linux-musl
sudo docker rm -f release-container
sudo docker image rm release-image
