version: 2.1

commands:
  slack_notify_failure:
    steps:
      - slack/notify:
          branch_pattern: main
          event: fail
          channel: 'engineering'
          custom: |-
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*:fire: ${CIRCLE_USERNAME} broke the Anonymiser ${CIRCLE_JOB} job :fire:*\n\n${GIT_COMMIT_MSG}"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://tenor.com/view/mochi-mochi-peach-cat-cat-kitty-animated-cry-gif-17774448",
                    "alt_text": "images"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }

orbs:
  slack: circleci/slack@4.5.1

notify:
  branches:
    only:
      - main


jobs:
  test:
    docker:
      - image: cimg/rust:1.62
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - checkout
      - run: echo 'export GIT_COMMIT_MSG="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
      - run: ./test
      - slack_notify_failure
      - store_test_results:
          path: results.xml

  build_release:
    docker:
      - image: cimg/rust:1.62
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - checkout
      - run: cargo build --release --target=x86_64-unknown-linux-gnu
      - store_artifacts:
          path: target/x86_64-unknown-linux-gnu/release/anonymiser
          destination: x86_64-unknown-linux-gnu

  build_release_macos:
    macos:
      xcode: 13.4.0
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - checkout
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run: rustup target add aarch64-apple-darwin
      - run: cargo build --release --target=x86_64-apple-darwin
      - run: cargo build --release --target=aarch64-apple-darwin
      - store_artifacts:
          path: target/x86_64-apple-darwin/release/anonymiser
          destination: x86_64-apple-darwin
      - store_artifacts:
          path: target/aarch64-apple-darwin/release/anonymiser
          destination: aarch64-apple-darwin

workflows:
  version: 2.4
  build:
    jobs:
      - test:
          context:
            - Default
      - build_release:
          context:
            - Default
      - build_release_macos:
          context:
            - Default
