version: 2.1

commands:
  slack_notify_failure:
    steps:
      - slack/notify:
          branch_pattern: main
          event: fail
          channel: 'engineering'
          custom: |-
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*:fire: ${CIRCLE_USERNAME} broke the Anonymiser ${CIRCLE_JOB} job :fire:*\n\n${GIT_COMMIT_MSG}"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://tenor.com/view/mochi-mochi-peach-cat-cat-kitty-animated-cry-gif-17774448",
                    "alt_text": "images"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }

orbs:
  slack: circleci/slack@4.5.1

notify:
  branches:
    only:
      - main


jobs:
  test:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run: echo 'export GIT_COMMIT_MSG="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
      - run: ./build
      - slack_notify_failure
      - store_test_results:
          path: results.xml
  create-release:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run: echo 'export GIT_COMMIT_MSG="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
      - run: ./create_releases
      - store_artifacts:
          path: ./anonymiser-aarch64-apple-darwin
          destination: anonymiser-aarch64-apple-darwin
      - store_artifacts:
          path: ./anonymiser-x86_64-unknown-linux-gnu
          destination: anonymiser-x86_64-unknown-linux-gnu
      - store_artifacts:
          path: ./anonymiser-x86_64-unknown-linux-musl
          destination: anonymiser-x86_64-unknown-linux-musl
      - slack_notify_failure

workflows:
  version: 2.4
  build:
    jobs:
      - test:
          context:
            - Default
      - create-release:
          context:
            - Default
          requires:
            - test
          filters:
            branches:
              only: main
