#!/bin/bash
brew tap SergioBenitez/osxct
brew install x86_64-unknown-linux-gnu
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc
cargo build --release --target=x86_64-unknown-linux-gnu
cp target/x86_64-unknown-linux-gnu/release/anonymiser ./anonymiser-x86_64-unknown-linux-gnu
