#!/bin/bash

if ! command -v cargo &> /dev/null
then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rust_setup
  chmod +x ./rust_setup
  ./rust_setup -y
  rm rust_step

  source ~/.bashrc
  cargo install cargo-watch
fi
